---
title: "Philosophy Excerpts for Pondering"
author: "Zhizhong ZZ Pu"
date: "Last updated: 2022"
output:
  html_document:
    theme: cerulean
    highlight: espresso
    toc: true
    toc_float: true
    collapsed: false
    smooth_scroll: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(Rmisc)

```

# Turgenev, Ivan (1818)
## Fathers and Children (1862)
A nihilist is a man who doesn’t acknowledge any authorities, who doesn’t accept a single principle on faith, no matter how much that principle may be surrounded by respect.

# Dostoevsky, Fyodor (1821)
## The Brothers Karamazov (1880)
'Decide for yourself who was right: You or the One who questioned You that day? Remember the first question, though not in literal terms, its sense was this: 'You want to go into the world and are going there with empty hands, with a kind of promise of freedom which they in their simplicity and inborn turpitude are unable even to comprehend, which they go in fear and awe of—for nothing has ever been more unendurable to man and human society than freedom!
Look, you see those stones in that naked, burning hot wilderness? Turn them into loaves and mankind will go trotting after you like a flock, grateful and obedient, though ever fearful that you may take away your hand and that your loaves may cease to come their way.' 
But you did not want to deprive man of freedom and rejected the offer, for what kind of freedom is it, you reasoned, if obedience is purchased with loaves? You retorted that man lives not by bread alone, but are you aware that in the name of that same earthly bread the Earth Spirit will rise up against you and fight with you and vanquish you, and everyone will follow it, crying: 'Who is like unto this beast, he has given us fire from heaven!' Are you aware that centuries will pass, and mankind will proclaim with the lips of its wisdom and science that there is no crime and consequently no sin either, but only the hungry.


# Camus, Albert (1913)
## Mythe de Sisyphe
**Il n'y a qu'un problème philosophique vraiment sérieux : c'est le suicide. Juger que la vie vaut ou ne vaut pas la peine d'être vécue, c'est répondre à la question fondamentale de la philosophie. Le reste, si le monde a trois dimensions, si l'esprit a neuf ou douze catégories, vient ensuite. Ce sont des jeux ; il faut d'abord répondre.** Et s'il est vrai, comme le veut Nietzsche, qu'un philosophe, pour être estimable, doive prêcher d'exemple, on saisit l'importance de cette réponse puisqu'elle va précéder le geste définitif. Ce sont là des évidences sensibles au cœur, mais qu'il faut approfondir pour les rendre claires à l'esprit. 

Si je me demande à quoi juger que telle question est plus pressante que telle autre, je réponds que c'est aux actions qu'elle engage.
Je n'ai jamais vu personne mourir pour l'argument ontologique. Galilée, qui tenait une vérité scientifique d'importance, l'abjura le plus aisément du monde dès qu'elle mit sa vie en péril. Dans un certain sens, il fit bien. Cette vérité ne valait pas le bûcher. **Qui de la terre ou du soleil tourne autour de l'autre, cela est profondément indifférent.** 

Il arrive que les décors s'écroulent. **Lever, tramway, quatre heures de bureau ou d'usine, repas, tramway, quatre heures de travail, repas, sommeil et lundi mardi mercredi jeudi vendredi et samedi sur le même rythme, cette route se suit aisément la plupart du temps. Un jour seulement, le « pourquoi » s'élève et tout commence dans cette lassitude teintée d'étonnement.** 
