---
title: Curriculum Vitae
---

## Education

- **Ph.D in Analytical Science**, University of Warwick, 2017
- **Double M.Sc. in Complex Systems Science**, École Polytechnique and Chalmers University of Technology, 2013
- **B.Eng. in Telecommunications Engineering**, Universidade Federal Fluminense, 2009

## Work experience

- **2022-present**: Manager, Imaging Applications, The Jackson Laboratory
    - Research IT department
- **2019-2022**: Systems Analyst, The Jackson Laboratory
    - Research IT department
- **2017-2019**: Research Fellow, University of Warwick
    - Division of Biomedical Sciences, Warwick Medical School
- **2017-2017**: Research Assistant, University of Warwick
    - Supervised by Prof. Rudolf Roemer, Department of Physics
- **2013-2017**: Ph.D candidate, University of Warwick
    - Supervised by Prof. Matthew Turner, Department of Physics
- **2008-2011**: Junior Engineer, Chemtech Ltda.
    - Telecommunications project design
- **2008-2008**: Research Intern, Harman/Becker GmbH.
    - Automotive applications

## Research experience

- **2019-present**: _Systems Analyst_, then _Manager, Imaging Applications, The Jackson Laboratory_
    - Leading a team of technical experts on institution-wide imaging data support
    - Developing novel Python libraries and command-line tools to interact with imaging data management platforms
    - Providing data analysis and data management advice and consultancy to ~60 research groups

- **2017-2019**: _Research Fellow on Bioimage analysis and data management, University of Warwick_
    - Responsible for image analysis and data management for the Biomedical Sciences division of Warwick Medical School
    - Implemented and maintained a number of IT systems for data management.
    - Developed software in multiple different languages to support image analysis needs from other researchers

- **2017**: _Research Assistant on protein structure visualisation, University of Warwick_
    - Developed a software pipeline to simulate and visualise protein rigidity analysis.
    - Built a virtual reality toolkit to deploy three-dimensional protein structure animations.
    - Took part in supporting antimicrobial resistance research, trying to understand how drugs affect protein rigidity.

- **2013-2017**: _Ph.D candidate in computational biophysics, University of Warwick_
    - Developed simulation software to better understand force generation during bacterial division.
    - Researched and adapted advanced applied mathematics algorithms for calculations.
    - Used high-performance computing infrastructure to achieve simulation results.


## Honors and Awards

- **2013**: Marie Sklodowska-Curie PhD Fellowship - Full tuition and stipend for 36 months and research-related expenses
- **2011**: Erasmus Mundus M.Sc. Scholarship - Full tuition and stipend for 24 months
- **2010**: Laurea Academica from Universidade Federal Fluminense - Awarded to best graduating student for each major
- **2009**: Premio Walder Moreira - ”Student of the year” award in Telecommunications Engineering
- **2007**: Premio Walder Moreira - ”Student of the year” award in Telecommunications Engineering