<h3><a style="text-decoration:underline" href="https://scholar.google.com/citations?user=7LY1_u4AAAAJ&hl=en">Google Scholar Profile</a></h3>

*Note: Please reach out to me over e-mail for PDFs not attached here/broken links*

## 2023
* Towards Scalable Identification of Brick Kilns from Satellite Imagery with Active Learning. Aditi Agarwal, Suraj Jaiswal, Madhav Kanda, Dhruv Patel, Rishabh Mondal, Vannsh Jani, Zeel B Patel, Nipun Batra and Sarath Guttikunda, In [RealWorldML](https://realworldml.github.io/neurips2023/) workshop, NeurIPS 2023 [[PDF]](https://github.com/patel-zeel/patel-zeel.github.io/blob/master/_publications/papers/Zeel_NeurIPS_Workshop_2023.pdf)
* Fine-Grained Spatio-Temporal Particulate Matter Dataset From Delhi For ML based Modeling. Sachin Chauhan, **Zeel B Patel**, Sayan Ranu, Rijurekha Sen, Nipun Batra, In NeurIPS 2023 (Datasets and Benchmarks). [[PDF]](https://github.com/patel-zeel/patel-zeel.github.io/blob/master/_publications/DelhiDatasetBenchmark.pdf)
* Conformal Prediction: A Visual Introduction. Mihir Agarwal, Lalit Routhu, **Zeel B Patel**, Nipun Batra, In VISxAI workshop 2023, IEEE VIS. [[URL]](https://conformal-prediction.streamlit.app/)
* Deep Gaussian Processes for Air Quality Inference. Aadesh Desai, Eshan Gujarathi, Saagar Parikh, Sachin Yadav, **Zeel Patel**, Nipun Batra. In CODS-COMAD 2023 Young Researchers Symposium track.

## 2022

* Uncertainty Disentanglement with Non-stationary Heteroscedastic Gaussian Processes for Active Learning. **Zeel B Patel**, Nipun Batra, Kevin Murphy. In NeurIPS Workshop on Gaussian Processes, Spatiotemporal Modeling, and Decision-making Systems 2022 [[arXiv](https://arxiv.org/abs/2210.10964)]

* Challenges in Gaussian Processes for Non Intrusive Load Monitoring. Aadesh Desai, Gautam Vashishtha, **Zeel B Patel**, Nipun Batra. In NeurIPS Workshop on Gaussian Processes, Spatiotemporal Modeling, and Decision-making Systems 2022 [[arXiv](https://arxiv.org/abs/2211.13018)]

* Samachar: Print News Media on Air Pollution in India. Karm Patel, Rishiraj Adhikary, **Zeel B Patel**, Nipun Batra, and Sarath Guttikunda. In ACM SIGCAS Computing and Sustainable Societies (COMPASS ’22) [[Publisher Link](https://dl.acm.org/doi/abs/10.1145/3530190.3534812)]

* Accurate and Scalable Gaussian Processes for Fine-grained Air Quality Inference. **Zeel B Patel**, Palak Purohit, Harsh Patel, Shivam Sahni, and Nipun Batra. AAAI 2022, Thirty-Sixth AAAI Conference on Artificial Intelligence (AAAI-22) (CORE A* with 15% acceptance rate) [[PDF](https://nipunbatra.github.io/papers/2022/aaai_22_air.pdf)] [[GitHub](https://github.com/patel-zeel/AAAI22)]

## 2021
* Towards Active Air Quality Station Deployment. **Zeel B Patel**, Nipun Batra. SubSetML Workshop, ICML 2021 (CORE A*) [[PDF](https://github.com/patel-zeel/patel-zeel.github.io/blob/master/_publications/papers/SubSetML21.pdf)]

* Vartalaap: what drives #AirQuality discussions: politics, pollution or pseudo-science? Rishiraj Adhikary, **Zeel B Patel**, Tanmay Srivastava, Nipun Batra, Mayank Singh, Udit Bhatia, and Sarath Guttikunda. ACM CSCW 2021 (CORE A) [[PDF](https://nipunbatra.github.io/papers/2021/vartalaap.pdf)] [[DOI](https://dl.acm.org/doi/abs/10.1145/3449170)]

## 2020
* Poster: A toolkit for spatial interpolation and sensor placement, **Zeel B Patel**, S Deepak Narayanan, Apoorv Agnihotri, Nipun Batra. ACM SenSys 2020 (CORE A*)[[PDF](https://github.com/patel-zeel/patel-zeel.github.io/blob/master/_publications/papers/polire.pdf)] [[DOI](https://dl.acm.org/doi/abs/10.1145/3384419.3430407)]

* Active Learning: A Visual Tour, **Zeel B Patel**, Nipun Batra. VisXAI Workshop, IEEE VIS 2020 (CORE A) [[URL](https://patel-zeel.github.io/active-learning-visualization)]
