[[news]]
date = "2026-04"
content = "My Chrome extension [QuickPage Capture](https://chromewebstore.google.com/detail/quickpage-capture/afaeaifhhnjeihopkbpffabdafbfgban?pli=1) is now available on the Chrome Web Store."
