
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-19T13:14:35-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fd3e7223514c66822077c0ac6394da6030e5b8b",
 "version": "1.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
